service: go-selfupdate

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    BUCKET_NAME: ${self:service}-${self:provider.stage}-updates
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:CopyObject
          Resource:
            - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt UpdateTrackingTable.Arn

package:
  patterns:
    - '!./**'
    - './lambda/**'

functions:
  promoteUpdate:
    handler: lambda/promote_update
    timeout: 30
    memorySize: 128
    events:
      - schedule:
          rate: rate(1 hour)
          enabled: true
          input:
            source: scheduler

resources:
  Resources:
    UpdatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        VersioningConfiguration:
          Status: Enabled
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

    UpdateTrackingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-tracking
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: version
            AttributeType: S
        KeySchema:
          - AttributeName: version
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

  Outputs:
    UpdatesBucketName:
      Description: "Name of the S3 bucket storing updates"
      Value: !Ref UpdatesBucket
    UpdateTrackingTableName:
      Description: "Name of the DynamoDB table tracking updates"
      Value: !Ref UpdateTrackingTable 